stages:
- validate
- plan
- apply

#only:
#- master

before_script:  
  - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
  - export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - sh pipeline/scripts/terraform-init.sh

Validate:
  stage: validate
  image: johnmorsley/alpine-with-terraform:0.14.2
  script:
  - sh pipeline/scripts/terraform-validate.sh

Plan:
  stage: plan
  image: johnmorsley/alpine-with-terraform:0.14.2
  script:
  - sh pipeline/scripts/terraform-plan.sh

Apply:
  stage: apply
  image: johnmorsley/alpine-with-terraform:0.14.2
  script:
  - sh pipeline/scripts/terraform-apply.sh